🎯 Objective

The objective of this project is to analyze employee data to extract meaningful insights for better workforce understanding and decision-making.

This analysis aims to:

    : How many total employees are there?

    : What is the average salary of employees?

    : Which employee has the highest salary?

    : What is the average salary for each department?

    : How many employees are there in each department?

    : Which city has the highest number of employees?

    : Find all employees with salary greater than 60000

    : Find employees with experience more than 4 years

    : Add a new column "Salary_Level" (High, Medium, Low based on salary)

    : Get top 3 highest paid employees

The goal is to simulate real-world HR analytics and support data-driven decision-making using data analysis techniques.

In [66]:
import pandas as pd

In [67]:
df=pd.read_csv("employee_data.csv")
df

   EmpID    Name Department  Salary  Experience       City
0   E101     Raj         IT   60000           3    Kolkata
1   E102  Simran         HR   40000           2      Delhi
2   E103    Amit    Finance   50000           4     Mumbai
3   E104   Pooja         IT   75000           5      Delhi
4   E105   Rohit         HR   42000           3    Kolkata
5   E106   Sneha    Finance   68000           6      Delhi
6   E107   Karan         IT   55000           2     Mumbai
7   E108    Neha    Finance   72000           7  Bangalore
8   E109   Vikas         HR   39000           1    Kolkata
9   E110    Riya         IT   80000           6      Delhi
10  E111   Ankit    Finance   52000           3     Mumbai
11  E112   Priya         HR   45000           4  Bangalore

In [68]:
print(df.columns)

Index(['EmpID', 'Name', 'Department', 'Salary', 'Experience', 'City'], dtype='object')

In [69]:
df.describe()

             Salary  Experience
count     12.000000   12.000000
mean   56500.000000    3.833333
std    14349.532777    1.850471
min    39000.000000    1.000000
25%    44250.000000    2.750000
50%    53500.000000    3.500000
75%    69000.000000    5.250000
max    80000.000000    7.000000

In [70]:
df.notnull()

    EmpID  Name  Department  Salary  Experience  City
0    True  True        True    True        True  True
1    True  True        True    True        True  True
2    True  True        True    True        True  True
3    True  True        True    True        True  True
4    True  True        True    True        True  True
5    True  True        True    True        True  True
6    True  True        True    True        True  True
7    True  True        True    True        True  True
8    True  True        True    True        True  True
9    True  True        True    True        True  True
10   True  True        True    True        True  True
11   True  True        True    True        True  True

In [71]:
#How many total employees are there?
total_employees=len(df)
print(total_employees)

12

Total number of employees in the dataset

In [72]:
#What is the average salary of employees?
average_salary=df['Salary'].mean()
print(average_salary)

56500.0

Average salary helps understand overall compensation level.

In [73]:
#Which employee has the highest salary?
highest_paid = df.loc[df['Salary'].idxmax()]
print(highest_paid)

EmpID          E110
Name           Riya
Department       IT
Salary        80000
Experience        6
City          Delhi
Name: 9, dtype: object

Identifies top-paid employee.

In [74]:
#What is the average salary for each department?
dept_avg=df.groupby("Department")['Salary'].mean()
print(dept_avg)

Department
Finance    60500.0
HR         41500.0
IT         67500.0
Name: Salary, dtype: float64

Helps compare departments financially.

In [75]:
#How many employees are there in each department?
dept_emp_count=df['Department'].count()
print(dept_emp_count)

12

In [76]:
#How many employees are there in each department?
dept_count = df['Department'].value_counts()
print(dept_count)

Department
IT         4
HR         4
Finance    4
Name: count, dtype: int64

In [77]:
#Which city has the highest number of employees?
city_count = df['City'].value_counts()
print(city_count)

top_city = city_count.idxmax()
print("City with highest employees:", top_city)

City
Delhi        4
Kolkata      3
Mumbai       3
Bangalore    2
Name: count, dtype: int64
City with highest employees: Delhi

In [78]:
#Find all employees with salary greater than 60000
high_salary=df[df['Salary']>60000]
print(high_salary)

  EmpID   Name Department  Salary  Experience       City
3  E104  Pooja         IT   75000           5      Delhi
5  E106  Sneha    Finance   68000           6      Delhi
7  E108   Neha    Finance   72000           7  Bangalore
9  E110   Riya         IT   80000           6      Delhi

Filters high-earning employees.

In [79]:
#Find employees with experience more than 4 years
experience_emp=df[df['Experience']>4]
print(experience_emp)

  EmpID   Name Department  Salary  Experience       City
3  E104  Pooja         IT   75000           5      Delhi
5  E106  Sneha    Finance   68000           6      Delhi
7  E108   Neha    Finance   72000           7  Bangalore
9  E110   Riya         IT   80000           6      Delhi

Identifies senior employees.

In [80]:
#Add a new column "Salary_Level" (High, Medium, Low based on salary)
def salary_level(salary):
    if salary > 70000:
        return "High"
    elif salary >= 50000:
        return "Medium"
    else:
        return "Low"

df['Salary_Level'] = df['Salary'].apply(salary_level)

In [81]:
df

   EmpID    Name Department  Salary  Experience       City Salary_Level
0   E101     Raj         IT   60000           3    Kolkata       Medium
1   E102  Simran         HR   40000           2      Delhi          Low
2   E103    Amit    Finance   50000           4     Mumbai       Medium
3   E104   Pooja         IT   75000           5      Delhi         High
4   E105   Rohit         HR   42000           3    Kolkata          Low
5   E106   Sneha    Finance   68000           6      Delhi       Medium
6   E107   Karan         IT   55000           2     Mumbai       Medium
7   E108    Neha    Finance   72000           7  Bangalore         High
8   E109   Vikas         HR   39000           1    Kolkata          Low
9   E110    Riya         IT   80000           6      Delhi         High
10  E111   Ankit    Finance   52000           3     Mumbai       Medium
11  E112   Priya         HR   45000           4  Bangalore          Low

In [82]:
#Get top 3 highest paid employees
top_3 = df.sort_values(by='Salary', ascending=False).head(3)
print(top_3)

  EmpID   Name Department  Salary  Experience       City Salary_Level
9  E110   Riya         IT   80000           6      Delhi         High
3  E104  Pooja         IT   75000           5      Delhi         High
7  E108   Neha    Finance   72000           7  Bangalore         High

In [83]:
# Save processed data
df.to_csv("processed_employee_data.csv", index=False)

In [85]:
df=pd.read_csv("processed_employee_data.csv")

In [86]:
df

   EmpID    Name Department  Salary  Experience       City Salary_Level
0   E101     Raj         IT   60000           3    Kolkata       Medium
1   E102  Simran         HR   40000           2      Delhi          Low
2   E103    Amit    Finance   50000           4     Mumbai       Medium
3   E104   Pooja         IT   75000           5      Delhi         High
4   E105   Rohit         HR   42000           3    Kolkata          Low
5   E106   Sneha    Finance   68000           6      Delhi       Medium
6   E107   Karan         IT   55000           2     Mumbai       Medium
7   E108    Neha    Finance   72000           7  Bangalore         High
8   E109   Vikas         HR   39000           1    Kolkata          Low
9   E110    Riya         IT   80000           6      Delhi         High
10  E111   Ankit    Finance   52000           3     Mumbai       Medium
11  E112   Priya         HR   45000           4  Bangalore          Low